name: "Metadata on the pull request event"
on:
  pull_request:
    types: [labeled, edited, synchronize]
    branches:
      - main

  workflow_dispatch:

jobs:
  validate_base_ref:
    runs-on: ubuntu-latest
    steps:
      - name: metadata
        run: |
          set -x
          echo base_ref: ${{github.base_ref}}
          echo head_ref: ${{github.head_ref}}
      - name: Validate that the base_ref is main
        if: ${{github.event_name == 'pull_request' }}
        run: |
          [ "${{github.base_ref}}" = "main" ]
